function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-May-2013 20:33:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0.749019622802734 0 0.749019622802734],...
    'MarkerEdgeColor',[0 0 1],...
    'Marker','o',...
    'Color',[1 0.694117647058824 0.392156862745098]);

